### ISSUE TITLE
HTML não deve definir a aparência

### ISSUE THREAD

**Issue by almino** [TailsonAlves/GuiLab#1]
Apesar do HTML ter tags e atributos que permitem alterar o visual de um elemento, essa prática é desaconselhada. Todas as instruções que alteram o visual de uma página devem ser feitas utilizando CSS. E, de preferência, num arquivo separado.

Lembrando que essas regras são apenas sugestões. Se o seu código tem atributos como `color`, `height` ou `width`, o navegador vai aceitar e tudo vai continuar funcionando normalmente.

As linhas que contém instruções para a aparência no HTML são:
- [land-page.html: 119](https://github.com/TailsonAlves/GuiLab/blob/5ea1beba376473048d74bf9e67eff713cba49e1e/land-page.html#L119)
- [land-page.html: 129](https://github.com/TailsonAlves/GuiLab/blob/5ea1beba376473048d74bf9e67eff713cba49e1e/land-page.html#L129)
- [land-page.html: 141](https://github.com/TailsonAlves/GuiLab/blob/5ea1beba376473048d74bf9e67eff713cba49e1e/land-page.html#L141)

**Comment by taialves** [comment]
Opa Almino, obrigado pelas dicas e sugestões! Com certeza irei aplicá-las nesse e nos demais projetos futuros, aperfeiçoando, assim, os códigos e melhorando as práticas de programação.

Edit: 
As alterações foram feitas, e as configurações de aparência foram colocadas em uma folha de estilo externa. Obrigado :+1:

**Comment by almino** [comment]
Vi aqui o [commit](https://github.com/TailsonAlves/GuiLab/commit/5ea1beba376473048d74bf9e67eff713cba49e1e) que tem a alteração. Parabéns, novamente!
